### ISSUE TITLE
Add method for checking preview mode

### ISSUE THREAD

**Issue by olga-nesterova** [ONLYOFFICE-QA/onlyoffice_documentserver_testing_framework#594]
Add method  [viewer?](https://github.com/ONLYOFFICE-QA/testing-documentserver/blob/4453f5869ffe28a46d02025dd53044cdc173ebcd/framework/management.rb#L50) for checking if document is currently in preview mode.

**Comment by ShockwaveNN** [comment]
Implemented [here](https://github.com/ONLYOFFICE-QA/onlyoffice_documentserver_testing_framework/pull/595)
